### ISSUE TITLE
Better name

### ISSUE THREAD

**Issue by gaborbernat** [tox-dev/tox-extra#1]
Hello, strict is a bit to uninformative I'd like to have it something else 🤔

**Comment by ssbarnea** [comment]
I am open to suggestions. I do not want to call it `tox-git` or `tox-dirty-status` because I am looking to use it for doing multiple unrelated checks before and after running tests. Naming it `tox-checks` would be even more confusing than `tox-strict`.

`tox --help | grep strict` did not return anything. Do you plan to add some kind of --strict mode to it in the future and that is why you want to avoid the confusion? That would be a good reason to find an alternative name.

**Comment by gaborbernat** [comment]
Mostly because strict does not tell you what it does. Maybe keep it tox-opinionated-ssbarnea 👍🏻 Ultimately many of these strict modes are opinionated checks. E.g. I'd not add ``tox-dirty-status`` feature into ``tox-strict``...

**Comment by ssbarnea** [comment]
The whole point of this plugin is to combine various simple checks and avoid the additional maintenance burden or having tons of small plugins. 

Most or these features are triggered only when needed and I plan to make them even optional if needed.

- dirty-status : used only when .git exists
- bindep run only when bindep.txt config file exists
- (planned) auto-wipe folders based on configured list of folders

I think that tox-extra will describe it better than tox-strict, as it adds some features that are not generic enough for core.
